### ISSUE TITLE
[Bug]: Crash Worldserver.exe at the beginning

### ISSUE THREAD

**Issue by Fireevil** [Gozzim/mod-globalchat#31]
### Current Behaviour

![Screenshot_45](https://user-images.githubusercontent.com/88008285/233908636-bd263b0e-8839-4617-bd63-15f15ed9fc33.jpg)

crash worldserver subcommand

### Expected Behaviour

.

### Steps to reproduce the problem

.

### Extra Notes

.

### AC rev. hash/commit

last Rev

### Operating system

windows 10

**Comment by Gozzim** [comment]
Please give me a detailed description of the problem.

The revision / commit hash

> last Rev

isn't helping me as time moves on and more pull requests are being merged.
Also fill out the section of `Custom changes or Modules` as you clearly are using at least one with the `mod-globalchat`

**Comment by Gozzim** [comment]
Works fine for me.

Closing due to invalid / missing information
